apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: contrast
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nodejs-base-image
        image: abhijeetatdhawale/aquila:1.0
        ports:
        - name: http
          containerPort: 3010
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
---

apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: contrast
  labels:
    app: eks-sample-linux-app
spec:
  type: NodePort
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010

---

apiVersion: v1
kind: Service
metadata:
  name: alb-eks-sample-linux-app
  namespace: contrast
  labels:
    app: eks-sample-linux-app
      #annotations:
      #service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  type: LoadBalancer  # Regular k8s Service manifest with type as LoadBalancer
  selector:
    app: eks-sample-linux-app   
  ports:
  - port: 80
    targetPort: 3010
